import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";

const credentials = process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY 
    ? {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
    }
    : undefined;

const sesClient = new SESClient({
    region: process.env.SES_REGION || process.env.AWS_REGION || "us-west-2",
    ...(credentials ? { credentials } : {})
});

let FROM_ADDRESS = process.env.SES_FROM_ADDRESS || "The Utility Network <founders@theutilitycompany.co>";
if ((FROM_ADDRESS.startsWith('"') && FROM_ADDRESS.endsWith('"')) || (FROM_ADDRESS.startsWith("'") && FROM_ADDRESS.endsWith("'"))) {
    FROM_ADDRESS = FROM_ADDRESS.substring(1, FROM_ADDRESS.length - 1);
}

// Extract the admin inbox from the FROM_ADDRESS for admin alerts
function getAdminEmail(): string {
    const match = FROM_ADDRESS.match(/<(.+?)>/);
    return match ? match[1] : 'founders@theutilitycompany.co';
}

// ============================================================================
// SHARED PREMIUM EMAIL TEMPLATE
// ============================================================================

function buildEmailHtml(heading: string, bodyContent: string, ctaUrl?: string, ctaLabel?: string): string {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://theutilitycompany.co';
    const nexusUrl = ctaUrl ? `${baseUrl}${ctaUrl}` : '';

    const ctaBlock = ctaUrl && ctaLabel ? `
                    <div style="text-align: center; margin: 32px 0;">
                        <a href="${nexusUrl}" style="display: inline-block; padding: 14px 36px; background: linear-gradient(135deg, #F54029 0%, #C53020 100%); color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 15px; box-shadow: 0 4px 14px rgba(245,64,41,0.3);">${ctaLabel}</a>
                    </div>` : '';

    return `
        <div style="background-color: #050505; padding: 60px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #ffffff;">
            <div style="max-width: 540px; margin: 0 auto; background-color: #0A0A0A; border-radius: 16px; overflow: hidden; border: 1px solid #222; box-shadow: 0 8px 32px rgba(0,0,0,0.5);">
                <!-- Header -->
                <div style="text-align: center; padding: 40px 20px 28px; border-bottom: 1px solid #1a1a1a; background: linear-gradient(180deg, #0f0f0f 0%, #0A0A0A 100%);">
                    <h1 style="color: #ffffff; font-size: 26px; font-weight: 800; margin: 0; letter-spacing: -0.5px;">TUC<span style="color: #F54029;"> NEXUS</span></h1>
                    <p style="color: #F54029; font-size: 11px; font-weight: 700; margin-top: 8px; margin-bottom: 0; text-transform: uppercase; letter-spacing: 3px;">The Utility Company</p>
                    <div style="width: 40px; height: 2px; background: linear-gradient(90deg, transparent, #F54029, transparent); margin: 16px auto 0; border-radius: 1px;"></div>
                </div>
                
                <!-- Body Content -->
                <div style="padding: 40px 30px;">
                    <h2 style="font-size: 20px; font-weight: 600; margin-top: 0; margin-bottom: 16px; color: #ffffff;">${heading}</h2>
                    ${bodyContent}
                    ${ctaBlock}
                </div>
                
                <!-- Footer -->
                <div style="padding: 24px 30px; text-align: center; background-color: #050505; border-top: 1px solid #1a1a1a;">
                    <p style="color: #3f3f46; font-size: 11px; margin: 0; line-height: 1.6;">
                        Securely generated by the TUC Nexus Platform.<br/>
                        &copy; ${new Date().getFullYear()} The Utility Company &middot; All rights reserved.
                    </p>
                </div>
            </div>
        </div>`;
}

function p(text: string): string {
    return `<p style="color: #a1a1aa; font-size: 15px; line-height: 1.6; margin-bottom: 16px;">${text}</p>`;
}

function strong(text: string): string {
    return `<strong style="color: #eee;">${text}</strong>`;
}

function muted(text: string): string {
    return `<p style="color: #71717a; font-size: 13px; line-height: 1.5; margin-bottom: 0;">${text}</p>`;
}

function badge(label: string, color: string = '#F54029'): string {
    return `<span style="display: inline-block; padding: 4px 12px; background-color: ${color}22; color: ${color}; border: 1px solid ${color}44; border-radius: 6px; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">${label}</span>`;
}

// ============================================================================
// CORE SEND
// ============================================================================

export async function sendEmail(to: string, subject: string, htmlBody: string): Promise<{ success: boolean; error?: string }> {
    try {
        const command = new SendEmailCommand({
            Destination: { ToAddresses: [to] },
            Message: {
                Body: { Html: { Charset: "UTF-8", Data: htmlBody } },
                Subject: { Charset: "UTF-8", Data: subject }
            },
            Source: FROM_ADDRESS
        });

        const response = await sesClient.send(command);
        console.log(`Email sent to ${to}. Message ID:`, response.MessageId);
        return { success: true };
    } catch (error: any) {
        console.error(`Failed to send email to ${to}:`, error);
        return { success: false, error: error.message || String(error) };
    }
}

/** Fire-and-forget bulk email sender for sets of recipients */
export async function sendBulkEmails(
    recipients: Set<string> | string[],
    subjectFn: (email: string) => string,
    htmlFn: (email: string) => string
): Promise<void> {
    const emails = Array.from(recipients);
    for (const email of emails) {
        sendEmail(email, subjectFn(email), htmlFn(email)).catch(err =>
            console.error(`[SES Bulk] Failed for ${email}:`, err)
        );
    }
}

// ============================================================================
// 1. PASSWORD RESET
// ============================================================================

export async function sendPasswordResetEmail(to: string, token: string) {
    const fallbackUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://theutilitycompany.co';
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || fallbackUrl;
    const resetUrl = token.startsWith('http') ? token : `${baseUrl}/nexus/reset-password?token=${token}`;

    const subject = "Password Reset requested for TUC Nexus";

    const ctaHtml = `<div style="text-align: center; margin: 32px 0;">
        <a href="${resetUrl}" style="display: inline-block; padding: 14px 36px; background: linear-gradient(135deg, #F54029 0%, #C53020 100%); color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 15px; box-shadow: 0 4px 14px rgba(245,64,41,0.3);">Reset Password</a>
    </div>`;

    const body = buildEmailHtml(
        'Reset your password',
        p(`We received a request to reset the password for your TUC Nexus account associated with ${strong(to)}. You can securely configure a new password by clicking the button below.`) +
        ctaHtml +
        muted('If you did not request this password reset, your account is perfectly safe. You can safely ignore this message. For security, this reset link will automatically expire in 2 hours.')
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 2. ACCREDITATION UPDATE
// ============================================================================

export async function sendAccreditationUpdateEmail(to: string, status: string, notes?: string) {
    const statusColors: Record<string, string> = { verified: '#22c55e', rejected: '#ef4444', pending: '#f59e0b' };
    const color = statusColors[status] || '#F54029';

    const subject = `Accreditation Review Update: ${status.toUpperCase()}`;
    const body = buildEmailHtml(
        'Accreditation Review Status Update',
        p(`Your accreditation status has been updated to: ${badge(status, color)}`) +
        (notes ? p(`${strong('Administrator Notes:')} ${notes}`) : '') +
        p('Please log in to your TUC Nexus dashboard to view details and proceed.'),
        '/nexus/dashboard',
        'View Dashboard'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 3. GOVERNANCE PROPOSAL
// ============================================================================

export async function sendProposalNotificationEmail(to: string, title: string) {
    const subject = `New Governance Proposal: ${title}`;
    const body = buildEmailHtml(
        'New Governance Proposal Requires Your Attention',
        p(`A new proposal titled ${strong(`"${title}"`)} has been published on the Cap Table and Governance module.`) +
        p('Please visit the TUC Nexus Cap Table dashboard to review the dilution impact and cast your vote.'),
        '/nexus/governance',
        'Review Proposal'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 4. INVESTOR REGISTRATION — Welcome + Admin Alert
// ============================================================================

export async function sendWelcomeEmail(to: string, fullName: string) {
    const subject = 'Application Received — TUC Nexus';
    const body = buildEmailHtml(
        `Welcome, ${fullName}`,
        p(`Thank you for submitting your investor application to ${strong('The Utility Company')}. Your application is now under review by our administrative team.`) +
        p('You will receive a follow-up email once your application has been reviewed and a decision has been made. This typically takes 1–2 business days.') +
        muted('If you have any questions in the meantime, please reply to this email.')
    );

    return sendEmail(to, subject, body);
}

export async function sendNewApplicationAdminAlert(applicantEmail: string, fullName: string, requestedRole: string) {
    const adminEmail = getAdminEmail();
    const subject = `[ACTION REQUIRED] New Investor Application: ${fullName}`;
    const body = buildEmailHtml(
        'New Application Requires Review',
        p(`A new application has been submitted and is pending your approval.`) +
        p(`${strong('Applicant:')} ${fullName}<br/>${strong('Email:')} ${applicantEmail}<br/>${strong('Requested Role:')} ${badge(requestedRole)}`),
        '/nexus/manage/team',
        'Review Application'
    );

    return sendEmail(adminEmail, subject, body);
}

// ============================================================================
// 5. APPLICATION APPROVED / SUSPENDED
// ============================================================================

export async function sendApplicationApprovedEmail(to: string, fullName: string, role: string) {
    const subject = 'Application Approved — TUC Nexus';
    const body = buildEmailHtml(
        'Your Application Has Been Approved',
        p(`Congratulations, ${strong(fullName)}! Your application to join TUC Nexus has been approved.`) +
        p(`You have been granted the role of ${badge(role)}. You can now log in and access all features available to your role.`),
        '/nexus/login',
        'Log In to Nexus'
    );

    return sendEmail(to, subject, body);
}

export async function sendApplicationSuspendedEmail(to: string, fullName: string) {
    const subject = 'Account Suspended — TUC Nexus';
    const body = buildEmailHtml(
        'Your Account Has Been Suspended',
        p(`Dear ${strong(fullName)}, your TUC Nexus account has been suspended by an administrator.`) +
        p('If you believe this is an error, please contact the TUC administrative team for further assistance.') +
        muted('You will not be able to log in until your account is reinstated.')
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 6. GOVERNANCE MEMOS / PROPOSALS / REPORTS
// ============================================================================

export async function sendMemoNotificationEmail(to: string, memoType: string, title: string, department: string, authorName: string, summary?: string, sourceId?: string) {
    const typeLabel = memoType.charAt(0).toUpperCase() + memoType.slice(1);
    const subject = `New ${typeLabel}: ${title}`;
    const body = buildEmailHtml(
        `New ${typeLabel} Requires Your Attention`,
        p(`A new ${memoType} has been submitted in the ${strong(department)} department.`) +
        p(`${strong('Title:')} ${title}<br/>${strong('Author:')} ${authorName}<br/>${strong('Type:')} ${badge(typeLabel)}`) +
        (summary ? p(`${strong('Summary:')} ${summary}`) : ''),
        `/nexus/governance?tab=memos${sourceId ? `&focus=${sourceId}` : ''}`,
        `View ${typeLabel}`
    );

    return sendEmail(to, subject, body);
}

export async function sendMemoStatusUpdateEmail(to: string, memoType: string, title: string, newStatus: string, sourceId?: string) {
    const typeLabel = memoType.charAt(0).toUpperCase() + memoType.slice(1);
    const statusColors: Record<string, string> = { published: '#F54029', approved: '#22c55e', rejected: '#ef4444', archived: '#71717a' };
    const color = statusColors[newStatus] || '#F54029';

    const subject = `${typeLabel} ${newStatus.charAt(0).toUpperCase() + newStatus.slice(1)}: ${title}`;
    const body = buildEmailHtml(
        `${typeLabel} Status Updated`,
        p(`Your ${memoType} ${strong(`"${title}"`)} has been updated to: ${badge(newStatus, color)}`),
        `/nexus/governance?tab=memos${sourceId ? `&focus=${sourceId}` : ''}`,
        `View ${typeLabel}`
    );

    return sendEmail(to, subject, body);
}

export async function sendMemoCommentEmail(to: string, memoType: string, title: string, commenterName: string, commentText: string, sourceId?: string) {
    const typeLabel = memoType.charAt(0).toUpperCase() + memoType.slice(1);
    const subject = `New Comment on ${typeLabel}: ${title}`;
    const body = buildEmailHtml(
        `New Comment on Your ${typeLabel}`,
        p(`${strong(commenterName)} posted a comment on your ${memoType} ${strong(`"${title}"`)}.`) +
        p(`<em style="color: #d4d4d8; border-left: 3px solid #F5402944; padding-left: 12px; display: block;">${commentText.length > 200 ? commentText.substring(0, 200) + '…' : commentText}</em>`) +
        p('Log in to view the full discussion and respond.'),
        `/nexus/governance?tab=memos${sourceId ? `&focus=${sourceId}` : ''}`,
        `View ${typeLabel}`
    );

    return sendEmail(to, subject, body);
}

export async function sendMemoResponseEmail(to: string, memoType: string, title: string, responderName: string, response: string, comment?: string, sourceId?: string) {
    const typeLabel = memoType.charAt(0).toUpperCase() + memoType.slice(1);
    const responseColors: Record<string, string> = { acknowledged: '#F54029', approved: '#22c55e', rejected: '#ef4444', comment: '#f59e0b' };
    const color = responseColors[response] || '#F54029';

    const subject = `${typeLabel} Response: ${responderName} — ${title}`;
    const body = buildEmailHtml(
        `Response to Your ${typeLabel}`,
        p(`${strong(responderName)} responded to your ${memoType} ${strong(`"${title}"`)}: ${badge(response, color)}`) +
        (comment ? p(`${strong('Comment:')} ${comment}`) : ''),
        `/nexus/governance?tab=memos${sourceId ? `&focus=${sourceId}` : ''}`,
        `View ${typeLabel}`
    );

    return sendEmail(to, subject, body);
}

export async function sendDocumentCommentEmail(to: string, documentTitle: string, commenterName: string, commentText: string, sourceId?: string) {
    const subject = `New Comment on Document: ${documentTitle}`;
    const body = buildEmailHtml(
        'New Comment on Your Document',
        p(`${strong(commenterName)} posted a comment on ${strong(`"${documentTitle}"`)}.`) +
        p(`<em style="color: #d4d4d8; border-left: 3px solid #F5402944; padding-left: 12px; display: block;">${commentText.length > 200 ? commentText.substring(0, 200) + '…' : commentText}</em>`) +
        p('Log in to view the full discussion.'),
        `/nexus/governance?tab=documents${sourceId ? `&focus=${sourceId}` : ''}`,
        'View Document'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 7. CORPORATE DOCUMENT UPLOADED
// ============================================================================

export async function sendDocumentUploadedEmail(to: string, title: string, uploaderName: string, description?: string, sourceId?: string) {
    const subject = `New Document: ${title}`;
    const body = buildEmailHtml(
        'New Corporate Document',
        p(`A new document has been uploaded to the corporate document vault.`) +
        p(`${strong('Document:')} ${title}<br/>${strong('Uploaded By:')} ${uploaderName}`) +
        (description ? p(`${strong('Description:')} ${description}`) : ''),
        `/nexus/governance?tab=documents${sourceId ? `&focus=${sourceId}` : ''}`,
        'View Document'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 8. SIGNATURE CEREMONY
// ============================================================================

export async function sendSignatureRequestEmail(to: string, signerName: string, documentTitle: string, requesterName: string, capacity?: string, message?: string, sourceId?: string) {
    const subject = `Signature Requested: ${documentTitle}`;
    const body = buildEmailHtml(
        'Your Signature Is Requested',
        p(`${strong(requesterName)} is requesting your signature${capacity ? ` as ${strong(capacity)}` : ''} on the document ${strong(`"${documentTitle}"`)}.`) +
        (message ? p(`${strong('Message:')} ${message}`) : '') +
        p('Please log in to TUC Nexus to review the document and complete the signing process.'),
        `/nexus/governance?tab=documents${sourceId ? `&sign=${sourceId}` : ''}`,
        'Review & Sign'
    );

    return sendEmail(to, subject, body);
}

export async function sendSignatureCompletedEmail(to: string, signerName: string, documentTitle: string, completedCount: number, totalCount: number, sourceId?: string) {
    const subject = `${signerName} Signed: ${documentTitle}`;
    const body = buildEmailHtml(
        'Signature Progress Update',
        p(`${strong(signerName)} has signed ${strong(`"${documentTitle}"`)}.`) +
        p(`Signature progress: ${strong(`${completedCount}/${totalCount}`)} complete.`),
        `/nexus/governance?tab=documents${sourceId ? `&sign=${sourceId}` : ''}`,
        'View Progress'
    );

    return sendEmail(to, subject, body);
}

export async function sendDocumentFullyExecutedEmail(to: string, documentTitle: string, signatoryCount: number, sourceId?: string) {
    const subject = `Document Fully Executed: ${documentTitle}`;
    const body = buildEmailHtml(
        'Document Fully Executed',
        p(`${strong(`"${documentTitle}"`)} has been signed by all ${strong(String(signatoryCount))} parties and is now ${badge('fully executed', '#22c55e')}.`) +
        p('A copy of the executed document is available in the corporate document vault.'),
        `/nexus/governance?tab=documents${sourceId ? `&sign=${sourceId}` : ''}`,
        'View Executed Document'
    );

    return sendEmail(to, subject, body);
}

export async function sendSignatureDeclinedEmail(to: string, declinerName: string, documentTitle: string, reason?: string, sourceId?: string) {
    const subject = `Signature Declined: ${documentTitle}`;
    const body = buildEmailHtml(
        'Signature Declined',
        p(`${strong(declinerName)} has ${badge('declined', '#ef4444')} to sign ${strong(`"${documentTitle}"`)}.`) +
        (reason ? p(`${strong('Reason:')} ${reason}`) : '') +
        p('Please review the signature request and take appropriate action.'),
        `/nexus/governance?tab=documents${sourceId ? `&sign=${sourceId}` : ''}`,
        'Review Request'
    );

    return sendEmail(to, subject, body);
}

export async function sendSignatureReminderEmail(to: string, signerName: string, documentTitle: string, requesterName: string, capacity?: string, sourceId?: string) {
    const subject = `Reminder: Signature Pending on ${documentTitle}`;
    const body = buildEmailHtml(
        'Signature Reminder',
        p(`${strong(requesterName)} is reminding you to sign ${strong(`"${documentTitle}"`)}${capacity ? ` as ${strong(capacity)}` : ''}.`) +
        p('Please log in to complete the signing process at your earliest convenience.'),
        `/nexus/governance?tab=documents${sourceId ? `&sign=${sourceId}` : ''}`,
        'Sign Now'
    );

    return sendEmail(to, subject, body);
}

export async function sendSignatureVoidedEmail(to: string, documentTitle: string, voiderName: string) {
    const subject = `Signature Request Voided: ${documentTitle}`;
    const body = buildEmailHtml(
        'Signature Request Voided',
        p(`The signature request for ${strong(`"${documentTitle}"`)} has been ${badge('voided', '#71717a')} by ${strong(voiderName)}.`) +
        muted('No further action is required on your part regarding this document.'),
        '/nexus/governance?tab=documents',
        'View Documents'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 9. RESOLUTIONS
// ============================================================================

export async function sendResolutionCreatedEmail(to: string, title: string, resolutionNumber: string, category: string, proposedBy: string, sourceId?: string) {
    const subject = `New Resolution: ${resolutionNumber} — ${title}`;
    const body = buildEmailHtml(
        'New Resolution Requires Your Review',
        p(`A new board resolution has been proposed and requires your attention.`) +
        p(`${strong('Resolution:')} ${resolutionNumber}<br/>${strong('Title:')} ${title}<br/>${strong('Category:')} ${badge(category)}<br/>${strong('Proposed By:')} ${proposedBy}`),
        `/nexus/governance?tab=resolutions${sourceId ? `&focus=${sourceId}` : ''}`,
        'Review Resolution'
    );

    return sendEmail(to, subject, body);
}

export async function sendResolutionOutcomeEmail(to: string, title: string, resolutionNumber: string, outcome: 'approved' | 'rejected', sourceId?: string) {
    const color = outcome === 'approved' ? '#22c55e' : '#ef4444';
    const subject = `Resolution ${outcome.charAt(0).toUpperCase() + outcome.slice(1)}: ${resolutionNumber}`;
    const body = buildEmailHtml(
        `Resolution ${outcome.charAt(0).toUpperCase() + outcome.slice(1)}`,
        p(`Board Resolution ${strong(resolutionNumber)} — ${strong(`"${title}"`)} — has been ${badge(outcome, color)}.`),
        `/nexus/governance?tab=resolutions${sourceId ? `&focus=${sourceId}` : ''}`,
        'View Resolution'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 10. BOARD MEETINGS
// ============================================================================

export async function sendMeetingScheduledEmail(to: string, title: string, meetingType: string, date: string, time?: string, location?: string) {
    const subject = `Board Meeting Scheduled: ${title}`;
    const body = buildEmailHtml(
        'Board Meeting Scheduled',
        p(`A new ${meetingType} board meeting has been scheduled.`) +
        p(`${strong('Meeting:')} ${title}<br/>${strong('Date:')} ${date}${time ? `<br/>${strong('Time:')} ${time}` : ''}${location ? `<br/>${strong('Location:')} ${location}` : ''}<br/>${strong('Type:')} ${badge(meetingType)}`),
        '/nexus/governance?tab=meetings',
        'View Meeting Details'
    );

    return sendEmail(to, subject, body);
}

// ============================================================================
// 11. INVESTMENT COMMITMENT
// ============================================================================

export async function sendInvestmentCommitmentEmail(to: string, fullName: string, campaignName: string, amount: number, instrument: string) {
    const subject = `Investment Commitment Confirmed: ${campaignName}`;
    const body = buildEmailHtml(
        'Investment Commitment Received',
        p(`Dear ${strong(fullName)}, your investment commitment has been recorded.`) +
        p(`${strong('Campaign:')} ${campaignName}<br/>${strong('Amount:')} $${amount.toLocaleString()}<br/>${strong('Instrument:')} ${badge(instrument)}`) +
        p('Your commitment is now pending settlement. You will receive further instructions regarding payment processing.'),
        '/nexus/dashboard',
        'View My Investments'
    );

    return sendEmail(to, subject, body);
}

export async function sendInvestmentCommitmentAdminAlert(campaignName: string, investorName: string, investorEmail: string, amount: number) {
    const adminEmail = getAdminEmail();
    const subject = `[NEW COMMITMENT] ${investorName} — $${amount.toLocaleString()} in ${campaignName}`;
    const body = buildEmailHtml(
        'New Investment Commitment',
        p(`A new investment commitment has been received.`) +
        p(`${strong('Investor:')} ${investorName}<br/>${strong('Email:')} ${investorEmail}<br/>${strong('Campaign:')} ${campaignName}<br/>${strong('Amount:')} $${amount.toLocaleString()}`),
        '/nexus/manage/team',
        'View Investor'
    );

    return sendEmail(adminEmail, subject, body);
}

// ============================================================================
// 12. DIRECT MESSAGES
// ============================================================================

export async function sendDirectMessageEmail(to: string, senderName: string, subject_line?: string) {
    const subject = `New Message from ${senderName} — TUC Nexus`;
    const body = buildEmailHtml(
        'You Have a New Message',
        p(`${strong(senderName)} has sent you a direct message on TUC Nexus.`) +
        (subject_line ? p(`${strong('Subject:')} ${subject_line}`) : '') +
        p('Log in to read and respond to the full message.'),
        '/nexus/dashboard',
        'View Messages'
    );

    return sendEmail(to, subject, body);
}
